# Generated by Django 6.0.4 on 2026-04-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prenom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("filiere", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("diplome", "Diplome"),
                        ],
                        default="actif",
                        max_length=20,
                    ),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                ("date_naissance", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_inscription"],
            },
        ),
    ]
